console.log('byee javascript');
a=345;
console.log(a);
console.log( typeof a);
message="be cool";
console.log(message);
console.log( typeof message);
isHungry=true;
console.log();
console.log(isHungry);
[x,y,z]=[2,3,4];
console.log(x+y+z);
console.log(2**4);
console.log(x**y);
console.log(1=='1');
console.log(1==='1');
console.log(1+'1'+1);
console.log(null+'1');
[y]=[4,5]
console.log(y);
